### ISSUE TITLE
Add support for .NET Framework 4.5.1 and above

### ISSUE THREAD

**Issue by kenns247** [watson-developer-cloud/dotnet-standard-sdk#88]
There appears to be no assembly references or content files that are compatible with 4.5.2 (or other) .NET Frameworks for the SpeechToText and ToneAnalyzer nuget packages. 
Support for v4.5.1 and above of the .NET Framework would be greatly advised and appreciated.

**Comment by Nazgaul** [comment]
The nuget package is not compatible with. Net 4.6.2

**Comment by mediumTaj** [comment]
@atilatosta Will this issue be resolved by the changes you're implementing?

**Comment by atilatosta** [comment]
@taj and @Nazgaul Unfortunately we will still not support 4.5.x, only from 4.6. This is because we have dependencies ([System.Net.WebSockets.Client](https://www.nuget.org/packages/System.Net.WebSockets.Client/4.3.0)) that are available only from version 1.3 of the standard .NET.

**Comment by cheawan** [comment]
Install-Package : Could not install package 'IBM.WatsonDeveloperCloud.VisualRecognition.v3 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any 
assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by mdumanoj** [comment]
Is there any updates about .NET v4.5.1 support?

**Comment by mediumTaj** [comment]
We transitioned to .NET Standard 2.0 in the major release. We should support up to .NET Platform 4.6.1.
